# Generated by Django 2.2.3 on 2019-10-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_createplotmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='createplotmodel',
            name='img',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
