# Generated by Django 2.2.3 on 2019-10-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_createplotmodel_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateFlattModel',
            fields=[
                ('flatno', models.IntegerField(primary_key=True, serialize=False)),
                ('roadno', models.IntegerField()),
                ('surveyno', models.IntegerField()),
                ('cstpersqyd', models.IntegerField()),
                ('totalsqyd', models.IntegerField()),
                ('expenses', models.IntegerField()),
                ('boundaries', models.IntegerField()),
                ('facing', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('totalcost', models.IntegerField()),
                ('img', models.ImageField(default=False, upload_to='')),
            ],
        ),
    ]
