# Generated by Django 2.2.3 on 2019-10-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_createflattmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateEmployeeModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('maillocation', models.EmailField(max_length=254)),
                ('doj', models.DateField()),
                ('locatio', models.CharField(default=False, max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=20)),
                ('remarks', models.CharField(max_length=30)),
            ],
        ),
    ]
